### ISSUE TITLE
make fails, missing rule for target experimental/optional

### ISSUE THREAD

**Issue by machineperson** [ef-gy/cxxhttp-example#1]
Hey,

I'm trying to get this example to compile, and `make` fails with this error message:

`make: *** No rule to make target `experimental/optional', needed by `example'.  Stop.`

I haven't quite wrapped my head around how the various makefiles are being generated, but in the `dependencies.mk` file I found
`experimental/optional`
as a line below a bunch of header file names. Possibly your makefile generation code is confused about the `<experimental/optional>` header that is being included somewhere?

I hope this is in any way helpful, if you need to know anything else or you think it may be a problem on my end, just let me know.

**Comment by EffinMaggie** [comment]
Ah, thanks!

Yes, the cxxhttp library briefly used std::optional, but it's in <experimental/optional> instead of clang. There was a makefile hack to generate a pretend header that would fix things up, but that only works if <experimental/optional> actually exists, and I presume Ubuntu didn't have that.

Can you do a clean checkout at HEAD? That should've fixed it now :).

**Comment by machineperson** [comment]
That does fix this particular problem - thanks for fixing it so quickly.
